linters:
  presets:
    # found in: golangci-lint help linters
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    # - style  # turned off, can be too much
    - test
    - unused
  disable:
    - cyclop
    - funlen
    - gocognit
    - nestif
    - exhaustruct  # TODO? annoying for now
    - perfsprint
    - err113  # TODO enable later
    - godot
    - depguard

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  govet:
    enable:
      - shadow
