# SPDX-FileCopyrightText: 2024 Tillitis AB <tillitis.se>
# SPDX-License-Identifier: BSD-2-Clause
version = 1

[[annotations]]
path = ".github/workflows/*"
SPDX-FileCopyrightText = "2022 Tillitis AB <tillitis.se>"
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = [
     ".clang-format",
     ".editorconfig",
     ".gitignore",
     ".golangci.yml",
     "Makefile",
     "README.md",
     "RELEASE.md",
     "go.mod",
     "go.sum",
     "apps/Makefile",
     "apps/blink/Makefile",
     "apps/nx/Makefile",
     "apps/rng_stream/Makefile",
     "apps/rng_stream/README.md",
     "apps/timer/Makefile",
     "apps/touch/Makefile",
     "system/60-tkey.rules",
     "test/requirements.txt"
]
SPDX-FileCopyrightText = "2022 Tillitis AB <tillitis.se>"
SPDX-License-Identifier = "BSD-2-Clause"
