
name: ci

on:
  push:
    branches:
      - 'main'
  pull_request: {}
  # allow manual runs:
  workflow_dispatch: {}

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tillitis/tkey-builder:2
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          # fetch-depth: 0
          persist-credentials: false

      - name: Clone tkey-libs
        uses: actions/checkout@v3
        with:
          repository: tillitis/tkey-libs
          ref: main
          path: tkey-libs

      - name: fix
        # https://github.com/actions/runner-images/issues/6775
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Build tkey-libs
        run: |
          cd tkey-libs
          make

      - name: make
        run: make -j LIBDIR=../tkey-libs

      - name: lint go code
        run: make lint

      - name: check fmt of c code
        run: make -C apps checkfmt

      - name: check for SPDX tags
        run: ./tools/spdx-ensure
